### ISSUE TITLE
Add a tasklist default filter for the dev profile and update the user-guide

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/engine#16]
When you start the stack for the first time, you have to add a "simple filter" in the tasklist menu. If you miss this step you couldn't see the result tasks.

We should document this step in the user guide and add a default filter when you use the "dev" profile of the engine.

**Comment by rseedorff** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a tasklist default filter](https://trello.com/c/tXmxctah/147-add-a-tasklist-default-filter)

**Comment by J12934** [comment]
Does this really make sense to restrict this to the dev profile?
Isn't this just as useful for production instances?
