### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by ruedih** [secureCodeBox/engine#18]
There are some vulnerable libs in the engine, we should do an update:
https://snyk.io/org/securecodebox/project/204877a9-5a34-43f1-adc4-b36b518c09f7/

**Comment by Trosky** [comment]
The Engine is currently running the deprecated 1.5.x version of spring boot.
All requirements are met to update to 2.x:
https://github.com/camunda/camunda-bpm-spring-boot-starter/releases/tag/3.0.0

**Comment by rseedorff** [comment]
This upgrade also comes with an upgrade to camunda 7.9 which has some great improvements for the external task handling. Let’s do it ;-)

**Comment by didaRatsimba** [comment]
Is this issue fixed ?

**Comment by rseedorff** [comment]
@didaRatsimba we are working on this: #41 but we have some issues to update our unit tests... Some of the dependend Testframeworks from camunda are having trouble with the new version.

**Comment by rseedorff** [comment]
https://blog.camunda.com/post/2018/12/camunda-spring-boot-starter-320-released/
https://blog.camunda.com/post/2018/11/camunda-bpm-7100-released/

**Comment by J12934** [comment]
The 7.9 to 7.10 migration docs specify some changes to the jar structure.
This might relate / help  with the problems we had with our custom styles while updating.

https://docs.camunda.org/manual/7.10/update/minor/79-to-710/#changed-webjar-structure

**Comment by MartinLang1** [comment]
Should be fixed and is merged into develop with: https://github.com/secureCodeBox/engine/pull/41
We can close the issue when merged to master

For further dependencies we should open a new issue.

**Comment by J12934** [comment]
All vulnerable dependencies with fixes available have been updated (in dev branch, stable release coming soon).

Will close this issue and keep an eye for snyk notifications once the remaining dependency has fixes available.
