### ISSUE TITLE
Pushing feature branches to hub docker is broken

### ISSUE THREAD

**Issue by wurstbrot** [secureCodeBox/engine#207]
**Describe the bug**

**To Reproduce**
Create a feature branch
Go to https://travis-ci.com/github/secureCodeBox/engine/builds/198668959 and check the logs:
`denied: requested access to the resource is denied`

**Expected behavior**
A push is performed

**Comment by J12934** [comment]
I've updated the permission for the technical user to include the engine again.
I'll restart the travis build for your branch.

**Comment by J12934** [comment]
Seems to have worked.
Your Docker Tag should be live now.
